#!/bin/bash

# Inject NVIDIA variables to bypass Proton boundaries
export __NV_PRIME_RENDER_OFFLOAD=1
export __VK_LAYER_NV_optimus=NVIDIA_only
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json

# Force XWayland session
export SDL_VIDEODRIVER=x11  # SDL2
export SDL_VIDEO_DRIVER=x11 # SDL3

# Set NVIDIA Performance Level 2
sudo nvidia-smi -lgc 210,1600
sudo nvidia-smi -lmc 810,6001

# Activate GameMode
dbus-send --session --dest=com.feralinteractive.GameMode --type=method_call /com/feralinteractive/GameMode com.feralinteractive.GameMode.RegisterGame int32:$$ >/dev/null 2>&1

# Execute script when a game launches
"$@"

# Deactivate GameMode
dbus-send --session --dest=com.feralinteractive.GameMode --type=method_call /com/feralinteractive/GameMode com.feralinteractive.GameMode.UnregisterGame int32:$$ >/dev/null 2>&1

# Reset NVIDIA Performance Level when closing the game (default: false)
# sudo nvidia-smi -rgc
# sudo nvidia-smi -rmc