#!/bin/bash

# Inject NVIDIA variables to bypass Proton boundaries
export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export VK_DRIVER_FILES=/usr/share/vulkan/icd.d/nvidia_icd.json

# Force XWayland session
export SDL_VIDEODRIVER=x11  # SDL2
export SDL_VIDEO_DRIVER=x11 # SDL3

# Dynamic symbol resolution for Proton/Wine
export MANGOHUD_DLSYM=1

# Disable Intel Turbo Boost, increase fan speed and set GPU PL limits
sudo systemctl start intel-noturbo.service
sudo systemctl start omen-maxfan.service
sudo systemctl start nvidia-limits.service

# Activate GameMode
dbus-send --session --dest=com.feralinteractive.GameMode --type=method_call /com/feralinteractive/GameMode com.feralinteractive.GameMode.RegisterGame int32:$$ >/dev/null 2>&1

# Execute script when a game launches
# If in Gaming Mode (Gamescope session), run without MangoHud to prevent double overlays
if [ -n "$GAMESCOPE_WAYLAND_DISPLAY" ] || [ "$XDG_CURRENT_DESKTOP" = "gamescope" ]; then
    "$@"
else
    # In Desktop Mode, inject MangoHud for MangoJuice control
    MANGOHUD=1 "$@"
fi

# Deactivate GameMode
dbus-send --session --dest=com.feralinteractive.GameMode --type=method_call /com/feralinteractive/GameMode com.feralinteractive.GameMode.UnregisterGame int32:$$ >/dev/null 2>&1

# Revert to previous state
sudo systemctl stop omen-maxfan.service
# sudo systemctl stop intel-noturbo.service (disabled)
# sudo systemctl stop nvidia-limits.service (disabled)